#include <exception>
#include <string>

using socket_exception = std::runtime_error;